/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import gsap from 'gsap'


export function Desktop(props) {
  const modelPath = `${import.meta.env.BASE_URL}models/Desktop.glb`
  const { nodes, materials } = useGLTF(modelPath)
  const { isMobile, ...groupProps } = props
  const scale = isMobile ? 0.8 : 2
  const toto = useRef()
  const baseY = useRef(null)

  // Gsap animation
  const drawerRef = useRef()
  const screenRef = useRef()
  const screen2Ref = useRef()
  const keyboardRef = useRef()
  const mouseRef = useRef()
  const paperRef = useRef()
  const paper2Ref = useRef()
  const paper3Ref = useRef()
  const paper4Ref = useRef()
  const leftTrophyRef = useRef()
  const rightTrophyRef = useRef()
  const shelfRef = useRef()
  const boardRef = useRef()
  const racketRef = useRef()
  const headRacketRef = useRef()
  const desktopRef = useRef()
  const penBlueRef = useRef()
  const penRedRef = useRef()
  const penGreenRef = useRef()
  const penContainerRef = useRef()
  const baseScreenSupportRef = useRef()
  const baseScreenSupport2Ref = useRef()
  const screenSupportRef = useRef()
  const screenSupport2Ref = useRef()
  const dogBowlRef = useRef()




  // 2. On lance l'animation
  useLayoutEffect(() => {
    const elements = [
      drawerRef.current, screenRef.current, screen2Ref.current,
      keyboardRef.current, mouseRef.current, paperRef.current,
      paper2Ref.current, paper3Ref.current, paper4Ref.current,
      leftTrophyRef.current, rightTrophyRef.current, shelfRef.current,
      boardRef.current, racketRef.current, headRacketRef.current,
      desktopRef.current, penBlueRef.current, penGreenRef.current,
      penRedRef.current, penContainerRef.current, baseScreenSupportRef.current,
      baseScreenSupport2Ref.current, screenSupportRef.current, screenSupport2Ref.current,
      dogBowlRef.current,
    ]

    if (elements.every(el => el != null)) {
      const tl = gsap.timeline({
        defaults: { duration: 1.2, ease: "back.out(1.7)" }
      })

     tl.fromTo(desktopRef.current.scale, { x: 0, y: 0, z: 0 }, { x: -1, y: -0.02, z: -0.475 }, 0)
  
  // Le décor du fond
  .fromTo([shelfRef.current.scale, boardRef.current.scale, drawerRef.current.scale], 
    { x: 0, y: 0, z: 0 }, 
    { x: (i) => [0.158, 0.567, 0.049][i], 
      y: (i) => [0.028, 0.028, 0.02][i], 
      z: (i) => [0.103, 0.268, 0.049][i], 
      stagger: 0.1 
    }, "-=1")

  // Supports Écran 1 & 2 (Base puis bras)
  .fromTo([baseScreenSupportRef.current.scale, baseScreenSupport2Ref.current.scale],
    { x: 0, y: 0, z: 0 }, { x: 0.195, y: 0.006, z: 0.149, stagger: 0.1 }, "-=0.8")
  .fromTo([screenSupportRef.current.scale, screenSupport2Ref.current.scale],
    { x: 0, y: 0, z: 0 }, { x: 0.062, y: 0.004, z: 0.065, stagger: 0.1 }, "-=1")

  // Les écrans
  .fromTo([screenRef.current.scale, screen2Ref.current.scale],
    { x: 0, y: 0, z: 0 }, { x: 0.436, y: 0.252, z: 0.011, stagger: 0.2 }, "-=0.8")

  // Accessoires de bureau
  .fromTo([keyboardRef.current.scale, mouseRef.current.scale],
    { x: 0, y: 0, z: 0 }, 
    { x: (i) => [-0.313, -0.046][i], y: -0.007, z: (i) => [-0.153, -0.072][i], stagger: 0.1 }, "-=1")

  // Pot et crayons (effet cascade)
  .fromTo(penContainerRef.current.scale, { x: 0, y: 0, z: 0 }, { x: 0.042, y: 0.042, z: 0.042 }, "-=0.8")
  .fromTo([penBlueRef.current.scale, penRedRef.current.scale, penGreenRef.current.scale],
    { x: 0, y: 0, z: 0 }, { x: -0.003, y: -0.044, z: -0.003, stagger: 0.1 }, "-=0.8")

  // Raquette, Trophées, Papiers et Gamelle
  .fromTo(racketRef.current.scale, { x: 0, y: 0, z: 0 }, { x: 1, y: 1, z: 1 }, "-=1")
  .fromTo(headRacketRef.current.scale, { x: 0, y: 0, z: 0 }, { x: -0.137, y: -0.005, z: -0.18 }, "-=1")
  .fromTo([leftTrophyRef.current.scale, rightTrophyRef.current.scale], { x: 0, y: 0, z: 0 }, { x: -0.062, y: -0.011, z: -0.055, stagger: 0.2 }, "-=0.8")
  .fromTo([paperRef.current.scale, paper2Ref.current.scale, paper3Ref.current.scale, paper4Ref.current.scale], { x: 0, y: 0, z: 0 }, { x: -0.096, y: 0, z: -0.15, stagger: 0.1 }, "-=1")
  .fromTo(dogBowlRef.current.scale, { x: 0, y: 0, z: 0 }, { x: 0.126, y: 0.029, z: 0.098 }, "-=0.5")



    }
  }, [])


  useFrame(({ clock }) => {
    if (!leftTrophyRef.current) return

    // On capture UNE SEULE FOIS la position initiale
    if (baseY.current === null) {
      baseY.current = leftTrophyRef.current.position.x
    }

    const t = clock.getElapsedTime()

    leftTrophyRef.current.position.x =
      baseY.current +
      Math.sin(t * 4) * Math.max(0, Math.sin(t * 0.5)) * 0.015
  })


  return (
    <group  {...props} dispose={null} scale={scale} rotation={[0.5, -1.2, 0.3]}>
      <mesh
        ref={drawerRef}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.011']}
        position={[0.775, 0.54, 0.521]}
        rotation={[-1.629, -1.123, 3.108]}
        scale={[0.049, 0.02, 0.049]}
      />
      <mesh
        ref={keyboardRef}
        castShadow
        receiveShadow
        geometry={nodes.Clavier.geometry}
        material={materials['Material.007']}
        position={[-0.006, 0.784, 0.13]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.313, -0.007, -0.153]}
      />
      <mesh
        ref={mouseRef}
        castShadow
        receiveShadow
        geometry={nodes.Souris.geometry}
        material={materials['Material.008']}
        position={[0.447, 0.784, 0.13]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.046, -0.007, -0.072]}
      />
      {/* Bureau */}
      <group
        ref={desktopRef}
        position={[0, 0.752, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.02, -0.475]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials['Material.003']}
        />
      </group>
      {/* Support ecran */}
      <mesh
        ref={screenSupportRef}
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.005']}
        position={[-0.368, 0.779, -0.318]}
        scale={[0.062, 0.004, 0.065]}
      />
      {/* Support ecran */}
      <mesh
        ref={baseScreenSupportRef}
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.006']}
        position={[-0.361, 0.779, -0.266]}
        scale={[0.195, 0.006, 0.149]}
      />
      <mesh
        ref={screenRef}
        castShadow
        receiveShadow
        geometry={nodes.Ecran.geometry}
        material={materials['Material.004']}
        position={[-0.347, 1.121, -0.239]}
        rotation={[0, 0.221, 0]}
        scale={[0.436, 0.252, 0.011]}
      />
      {/* Support ecran */}
      <mesh
        ref={baseScreenSupport2Ref}
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['Material.014']}
        position={[0.489, 0.779, -0.266]}
        scale={[0.195, 0.006, 0.149]}
      />
      <mesh
        ref={screen2Ref}
        castShadow
        receiveShadow
        geometry={nodes.Ecran001.geometry}
        material={materials['Material.012']}
        position={[0.51, 1.121, -0.194]}
        rotation={[0, -0.317, 0]}
        scale={[0.436, 0.252, 0.011]}
      />
      {/* Support ecran */}
      <mesh
        ref={screenSupport2Ref}
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Material.013']}
        position={[0.509, 0.779, -0.295]}
        rotation={[0, -0.243, 0]}
        scale={[0.062, 0.004, 0.065]}
      />
      {/* Raquette */}
      <group ref={racketRef} position={[-0.566, 1.815, -0.542]} rotation={[0.053, 0.026, -0.001]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials['Material.016']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials['Material.017']}
        />
      </group>
      {/* tete de raquette */}
      <mesh
        ref={headRacketRef}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.018']}
        position={[0.242, 1.845, -0.547]}
        rotation={[1.792, -1.473, -2.902]}
        scale={[-0.137, -0.005, -0.18]}
      />
      {/* trophée */}
      <mesh
        ref={rightTrophyRef}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.010']}
        position={[-0.86, 1.525, -0.56]}
        scale={[-0.041, -0.007, -0.036]}
      />
      {/* Support trophée */}
      <mesh
        ref={shelfRef}
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.009']}
        position={[-0.963, 1.494, -0.553]}
        scale={[0.158, 0.028, 0.103]}
      />
      {/* Trophee */}
      <mesh
        ref={leftTrophyRef}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material.015']}
        position={[-1.019, 1.527, -0.56]}
        scale={[-0.062, -0.011, -0.055]}
      />
      {/* Feuilles */}
      <mesh
        ref={paper4Ref}
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.001']}
        position={[-0.487, 0.775, 0.196]}
        rotation={[0, -0.206, 0]}
        scale={[-0.096, 0, -0.15]}
      />
      {/* Feuilles */}
      <mesh
        ref={paper3Ref}
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.002']}
        position={[-0.781, 0.776, 0.302]}
        rotation={[0, 0.78, 0]}
        scale={[-0.096, 0, -0.15]}
      />
      {/* Feuilles */}
      <mesh
        ref={paperRef}
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.019']}
        position={[-0.765, 0.776, 0.196]}
        rotation={[0, 0.21, 0]}
        scale={[-0.096, 0, -0.15]}
      />
      {/* Feuilles */}
      <mesh
        ref={paper2Ref}
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.020']}
        position={[-0.607, 0.776, 0.244]}
        rotation={[0, 0.21, 0]}
        scale={[-0.096, 0, -0.15]}
      />
      {/* Tableau */}
      <mesh
        ref={boardRef}
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Material.021']}
        position={[-0.068, 1.807, -0.553]}
        rotation={[1.555, 0, 0]}
        scale={[0.567, 0.028, 0.268]}
      />
      {/* Pot crayon */}
      <mesh
        ref={penContainerRef}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material.022']}
        position={[0.748, 0.815, 0.063]}
        scale={0.042}
      />
      {/* Crayon rouge */}
      <group
        ref={penRedRef}
        position={[0.736, 0.822, 0.047]}
        rotation={[0.108, -0.563, 0.542]}
        scale={[-0.003, -0.044, -0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015.geometry}
          material={materials['Material.023']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials['Material.024']}
        />
      </group>
      {/* Crayon vert */}
      <group
        ref={penGreenRef}
        position={[0.748, 0.822, 0.037]}
        rotation={[-0.342, 0, 0]}
        scale={[-0.003, -0.044, -0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={materials['Material.026']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_1.geometry}
          material={materials['Material.025']}
        />
      </group>
      {/* Crayon bleu */}
      <group
        ref={penBlueRef}
        position={[0.772, 0.833, 0.045]}
        rotation={[-0.425, 0, 0]}
        scale={[-0.003, -0.044, -0.003]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials['Material.028']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={materials['Material.027']}
        />
      </group>
      {/* gamelle chien */}
      <mesh
        ref={dogBowlRef}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials['Material.031']}
        position={[-0.874, -0.078, 0.734]}
        rotation={[Math.PI, -0.98, Math.PI]}
        scale={[0.126, 0.029, 0.098]}
      />
    </group>
  )
}

useGLTF.preload('/models/Desktop.glb')